export type Option = { value: string; label: string };

export type CountryGroup = {
  continent: string;
  countries: Option[];
};

export const COUNTRY_GROUPS: CountryGroup[] = [
  {
    continent: "Africa",
    countries: [
      { value: "DZ", label: "Algeria" },
      { value: "AO", label: "Angola" },
      { value: "BJ", label: "Benin" },
      { value: "BW", label: "Botswana" },
      { value: "BF", label: "Burkina Faso" },
      { value: "BI", label: "Burundi" },
      { value: "CV", label: "Cabo Verde" },
      { value: "CM", label: "Cameroon" },
      { value: "CF", label: "Central African Republic" },
      { value: "TD", label: "Chad" },
      { value: "KM", label: "Comoros" },
      { value: "CG", label: "Congo" },
      { value: "CD", label: "Congo (Democratic Republic)" },
      { value: "CI", label: "Côte d'Ivoire" },
      { value: "DJ", label: "Djibouti" },
      { value: "EG", label: "Egypt" },
      { value: "GQ", label: "Equatorial Guinea" },
      { value: "ER", label: "Eritrea" },
      { value: "SZ", label: "Eswatini" },
      { value: "ET", label: "Ethiopia" },
      { value: "GA", label: "Gabon" },
      { value: "GM", label: "Gambia" },
      { value: "GH", label: "Ghana" },
      { value: "GN", label: "Guinea" },
      { value: "GW", label: "Guinea-Bissau" },
      { value: "KE", label: "Kenya" },
      { value: "LS", label: "Lesotho" },
      { value: "LR", label: "Liberia" },
      { value: "LY", label: "Libya" },
      { value: "MG", label: "Madagascar" },
      { value: "MW", label: "Malawi" },
      { value: "ML", label: "Mali" },
      { value: "MR", label: "Mauritania" },
      { value: "MU", label: "Mauritius" },
      { value: "YT", label: "Mayotte" },
      { value: "MA", label: "Morocco" },
      { value: "MZ", label: "Mozambique" },
      { value: "NA", label: "Namibia" },
      { value: "NE", label: "Niger" },
      { value: "NG", label: "Nigeria" },
      { value: "RE", label: "Réunion" },
      { value: "RW", label: "Rwanda" },
      { value: "SH", label: "Saint Helena" },
      { value: "SN", label: "Senegal" },
      { value: "SC", label: "Seychelles" },
      { value: "SL", label: "Sierra Leone" },
      { value: "SO", label: "Somalia" },
      { value: "ZA", label: "South Africa" },
      { value: "SS", label: "South Sudan" },
      { value: "SD", label: "Sudan" },
      { value: "TZ", label: "Tanzania" },
      { value: "TG", label: "Togo" },
      { value: "TN", label: "Tunisia" },
      { value: "UG", label: "Uganda" },
      { value: "ZM", label: "Zambia" },
      { value: "ZW", label: "Zimbabwe" },
    ],
  },

  {
    continent: "Asia",
    countries: [
      { value: "AF", label: "Afghanistan" },
      { value: "AM", label: "Armenia" },
      { value: "AZ", label: "Azerbaijan" },
      { value: "BH", label: "Bahrain" },
      { value: "BD", label: "Bangladesh" },
      { value: "BT", label: "Bhutan" },
      { value: "BN", label: "Brunei" },
      { value: "KH", label: "Cambodia" },
      { value: "CN", label: "China" },
      { value: "CY", label: "Cyprus" },
      { value: "GE", label: "Georgia" },
      { value: "HK", label: "Hong Kong" },
      { value: "IN", label: "India" },
      { value: "ID", label: "Indonesia" },
      { value: "IR", label: "Iran" },
      { value: "IQ", label: "Iraq" },
      { value: "IL", label: "Israel" },
      { value: "JP", label: "Japan" },
      { value: "JO", label: "Jordan" },
      { value: "KZ", label: "Kazakhstan" },
      { value: "KW", label: "Kuwait" },
      { value: "KG", label: "Kyrgyzstan" },
      { value: "LA", label: "Laos" },
      { value: "LB", label: "Lebanon" },
      { value: "MO", label: "Macao" },
      { value: "MY", label: "Malaysia" },
      { value: "MV", label: "Maldives" },
      { value: "MN", label: "Mongolia" },
      { value: "MM", label: "Myanmar" },
      { value: "NP", label: "Nepal" },
      { value: "KP", label: "North Korea" },
      { value: "OM", label: "Oman" },
      { value: "PK", label: "Pakistan" },
      { value: "PS", label: "Palestine" },
      { value: "PH", label: "Philippines" },
      { value: "QA", label: "Qatar" },
      { value: "SA", label: "Saudi Arabia" },
      { value: "SG", label: "Singapore" },
      { value: "KR", label: "South Korea" },
      { value: "LK", label: "Sri Lanka" },
      { value: "SY", label: "Syria" },
      { value: "TW", label: "Taiwan" },
      { value: "TJ", label: "Tajikistan" },
      { value: "TH", label: "Thailand" },
      { value: "TL", label: "Timor-Leste" },
      { value: "TR", label: "Turkey" },
      { value: "TM", label: "Turkmenistan" },
      { value: "AE", label: "United Arab Emirates" },
      { value: "UZ", label: "Uzbekistan" },
      { value: "VN", label: "Vietnam" },
      { value: "YE", label: "Yemen" },
    ],
  },

  {
    continent: "Europe",
    countries: [
      { value: "AL", label: "Albania" },
      { value: "AD", label: "Andorra" },
      { value: "AT", label: "Austria" },
      { value: "BY", label: "Belarus" },
      { value: "BE", label: "Belgium" },
      { value: "BA", label: "Bosnia and Herzegovina" },
      { value: "BG", label: "Bulgaria" },
      { value: "HR", label: "Croatia" },
      { value: "CZ", label: "Czechia" },
      { value: "DK", label: "Denmark" },
      { value: "EE", label: "Estonia" },
      { value: "FI", label: "Finland" },
      { value: "FR", label: "France" },
      { value: "DE", label: "Germany" },
      { value: "GR", label: "Greece" },
      { value: "HU", label: "Hungary" },
      { value: "IS", label: "Iceland" },
      { value: "IE", label: "Ireland" },
      { value: "IT", label: "Italy" },
      { value: "LV", label: "Latvia" },
      { value: "LI", label: "Liechtenstein" },
      { value: "LT", label: "Lithuania" },
      { value: "LU", label: "Luxembourg" },
      { value: "MT", label: "Malta" },
      { value: "MD", label: "Moldova" },
      { value: "MC", label: "Monaco" },
      { value: "ME", label: "Montenegro" },
      { value: "NL", label: "Netherlands" },
      { value: "MK", label: "North Macedonia" },
      { value: "NO", label: "Norway" },
      { value: "PL", label: "Poland" },
      { value: "PT", label: "Portugal" },
      { value: "RO", label: "Romania" },
      { value: "RU", label: "Russia" },
      { value: "SM", label: "San Marino" },
      { value: "RS", label: "Serbia" },
      { value: "SK", label: "Slovakia" },
      { value: "SI", label: "Slovenia" },
      { value: "ES", label: "Spain" },
      { value: "SE", label: "Sweden" },
      { value: "CH", label: "Switzerland" },
      { value: "UA", label: "Ukraine" },
      { value: "GB", label: "United Kingdom" },
      { value: "VA", label: "Vatican City" },
    ],
  },

  {
    continent: "North America",
    countries: [
      { value: "AG", label: "Antigua and Barbuda" },
      { value: "BS", label: "Bahamas" },
      { value: "BB", label: "Barbados" },
      { value: "BZ", label: "Belize" },
      { value: "CA", label: "Canada" },
      { value: "CR", label: "Costa Rica" },
      { value: "CU", label: "Cuba" },
      { value: "DM", label: "Dominica" },
      { value: "DO", label: "Dominican Republic" },
      { value: "SV", label: "El Salvador" },
      { value: "GD", label: "Grenada" },
      { value: "GT", label: "Guatemala" },
      { value: "HT", label: "Haiti" },
      { value: "HN", label: "Honduras" },
      { value: "JM", label: "Jamaica" },
      { value: "MX", label: "Mexico" },
      { value: "NI", label: "Nicaragua" },
      { value: "PA", label: "Panama" },
      { value: "KN", label: "Saint Kitts and Nevis" },
      { value: "LC", label: "Saint Lucia" },
      { value: "VC", label: "Saint Vincent and the Grenadines" },
      { value: "TT", label: "Trinidad and Tobago" },
      { value: "US", label: "United States" },
    ],
  },

  {
    continent: "South America",
    countries: [
      { value: "AR", label: "Argentina" },
      { value: "BO", label: "Bolivia" },
      { value: "BR", label: "Brazil" },
      { value: "CL", label: "Chile" },
      { value: "CO", label: "Colombia" },
      { value: "EC", label: "Ecuador" },
      { value: "GY", label: "Guyana" },
      { value: "PY", label: "Paraguay" },
      { value: "PE", label: "Peru" },
      { value: "SR", label: "Suriname" },
      { value: "UY", label: "Uruguay" },
      { value: "VE", label: "Venezuela" },
    ],
  },

  {
    continent: "Oceania",
    countries: [
      { value: "AU", label: "Australia" },
      { value: "FJ", label: "Fiji" },
      { value: "KI", label: "Kiribati" },
      { value: "MH", label: "Marshall Islands" },
      { value: "FM", label: "Micronesia" },
      { value: "NR", label: "Nauru" },
      { value: "NZ", label: "New Zealand" },
      { value: "PW", label: "Palau" },
      { value: "PG", label: "Papua New Guinea" },
      { value: "WS", label: "Samoa" },
      { value: "SB", label: "Solomon Islands" },
      { value: "TO", label: "Tonga" },
      { value: "TV", label: "Tuvalu" },
      { value: "VU", label: "Vanuatu" },
    ],
  },
];

// Flattened list (for simple selects)
const PRIORITY = ["US", "CA"];

export const COUNTRIES: Option[] = COUNTRY_GROUPS
  .flatMap((group) => group.countries)
  .sort((a, b) => {
    const aPriority = PRIORITY.includes(a.value) ? 0 : 1;
    const bPriority = PRIORITY.includes(b.value) ? 0 : 1;

    if (aPriority !== bPriority) return aPriority - bPriority;

    return a.label.localeCompare(b.label, undefined, { sensitivity: "base" });
  });

// Validation set
export const COUNTRY_SET = new Set(COUNTRIES.map((c) => c.value));