export const MEASUREMENT_HELP: Record<string, { label: string; img: string; tip: string }> = {
  heightIn: { label: "Height", img: "/measurements/height.png", tip: "Stand straight. Measure from top of head to floor." },
  bustIn: { label: "Bust", img: "/measurements/bust.png", tip: "Around the fullest part of the bust." },
  waistIn: { label: "Waist", img: "/measurements/waist.png", tip: "Natural waistline (smallest part)." },
  hipsIn: { label: "Hips", img: "/measurements/hips.png", tip: "Around the widest part of hips/seat." },
  shoulderToNippleIn: { label: "Shoulder → nipple", img: "/measurements/shoulderToNipple.png", tip: "From shoulder point down to nipple." },
  shoulderToUnderbustIn: { label: "Shoulder → underbust", img: "/measurements/shoulderToUnderbust.png", tip: "From shoulder point to underbust line." },
  shoulderToWaistIn: { label: "Shoulder → waist", img: "/measurements/shoulderToWaist.png", tip: "From shoulder point to natural waist." },
  aroundBellyButtonIn: { label: "Around belly button", img: "/measurements/aroundBellyButton.png", tip: "Around torso at navel level." },
  aroundLowerBellyIn: { label: "Around lower belly", img: "/measurements/aroundLowerBelly.png", tip: "Around the lower abdomen." },
  acrossBackIn: { label: "Across back", img: "/measurements/acrossBack.png", tip: "Across the back from armpit crease to armpit crease." },
  aroundArmIn: { label: "Around arm", img: "/measurements/aroundArm.png", tip: "Around the widest part of upper arm." },
  sleeveLengthIn: { label: "Sleeve length", img: "/measurements/sleeveLength.png", tip: "From shoulder seam to wrist." },
  shoulderToButtIn: { label: "Shoulder → butt", img: "/measurements/shoulderToButt.png", tip: "From shoulder point down to fullest part of seat." },
  fullLengthIn: { label: "Full height of the garment", img: "/measurements/fullLength.png", tip: "Use if requested by dressmaker." },
};